# Generated by Django 5.2.3 on 2025-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joballotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
