# Generated by Django 5.2.3 on 2025-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joballotment', '0002_job_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
